# Generated by Django 5.0.6 on 2024-07-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statelist_app', '0005_comentary_coment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentary',
            old_name='coment_user',
            new_name='comentary_user',
        ),
    ]
