# Generated by Django 5.0.6 on 2024-08-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statelist_app', '0006_rename_coment_user_comentary_comentary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='edification',
            name='avg_calification',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='edification',
            name='number_calification',
            field=models.IntegerField(default=0),
        ),
    ]
